"""empty message

Revision ID: 33eb655918d7
Revises: e81046f3e652
Create Date: 2024-08-08 21:09:39.906006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33eb655918d7'
down_revision = 'e81046f3e652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birthDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthDate', sa.DATE(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
