"""empty message

Revision ID: 538457f3dbf4
Revises: 3b0fdb45b4f5
Create Date: 2024-07-29 19:41:23.086194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538457f3dbf4'
down_revision = '3b0fdb45b4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
