"""empty message

Revision ID: 846865a389fb
Revises: 33eb655918d7
Create Date: 2024-08-08 21:16:12.452984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846865a389fb'
down_revision = '33eb655918d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
