"""empty message

Revision ID: 98d15031e0d1
Revises: 0d3539c6b384
Create Date: 2024-07-22 15:42:55.085632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d15031e0d1'
down_revision = '0d3539c6b384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('birthDate', sa.DateTime(timezone=120), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('postalCode', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['postalCode'])
        batch_op.create_unique_constraint(None, ['lastName'])
        batch_op.create_unique_constraint(None, ['firstName'])
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['birthDate'])
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.create_unique_constraint(None, ['country'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('postalCode')
        batch_op.drop_column('country')
        batch_op.drop_column('birthDate')
        batch_op.drop_column('phone')
        batch_op.drop_column('username')
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    # ### end Alembic commands ###
