"""empty message

Revision ID: c71021e0c238
Revises: 43f1be96f432
Create Date: 2024-08-07 16:12:39.256984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71021e0c238'
down_revision = '43f1be96f432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_apiId_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_unique_constraint('favorite_apiId_key', ['apiId'])

    # ### end Alembic commands ###
