"""empty message

Revision ID: e75864e32e25
Revises: 846865a389fb
Create Date: 2024-08-08 23:14:19.580231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75864e32e25'
down_revision = '846865a389fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
